resolver: lts-8.4
packages:
- '.'
- location:
    git: https://github.com/v0d1ch/yesod-auth-oauth2.git
    commit: 63ebd7d60e117ba5bc3ebbea59fc45b5782326d

extra-deps: [
     yesod-text-markdown-0.1.8
   , load-env-0.1.1
   , aeson-0.11.3.0
]

flags: {}
extra-package-dbs: []
