static-dir:     "_env:STATIC_DIR:static"
host:           "_env:HOST:*4" # any IPv4 host
port:           "_env:PORT:3000" # NB: The port `yesod devel` uses is distinct from this value. Set the `yesod devel` port from the command line.
ip-from-header: "_env:IP_FROM_HEADER:false"

ssl: true
database:
  # See config/test-settings.yml for an override during tests
  database: "_env:SQLITE_DATABASE:haskell-serbia-sqlite.sqlite3"
  poolsize: "_env:SQLITE_POOLSIZE:100"

copyright: Haskell Srbija 2017
#analytics: UA-YOURCODE

oauth2:
  - provider: "github"
    id:       "_env:GITHUB_CLIENT_ID: ************"
    secret:   "_env:GITHUB_CLIENT_SECRET:***********************"
