Default: &defaults
  database: haskell-serbia.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: haskell_serbia_test.sqlite3
  <<: *defaults

Staging:
  database: haskell_serbia_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: haskell_serbia_production.sqlite3
  poolsize: 100
  <<: *defaults
