database:
  # NOTE: By design, this setting prevents the SQLITE_DATABASE environment variable
  # from affecting test runs, so that we don't accidentally affect the
  # production database during testing. If you're not concerned about that and
  # would like to have environment variable overrides, you could instead use
  # something like:
  #
  #   database: "_env:SQLITE_DATABASE:haskell-serbia_test.sqlite3"
  # database: haskell-serbia_test.sqlite3
  user:     "_env:PGUSER:yesod"
  password: "_env:PGPASS: 8888_haskel_serbia"
  host:     "_env:PGHOST:localhost"
  port:     "_env:PGPORT:5432"
  database: "_env:PGDATABASE:haskell_serbia_test"
  poolsize: "_env:PGPOOLSIZE:10"

auth-dummy-login: true
